import React,{useEffect,useMemo,useState} from 'react';
import {MapContainer,TileLayer,CircleMarker,Popup} from 'react-leaflet';
import projects from './projects.json';

const LGA_COORDS={
  'Gombe':[10.2897,11.1673],'Akko':[10.049,11.210],'Balanga':[9.887,11.544],'Billiri':[9.865,11.225],
  'Dukku':[10.823,10.772],'Funakaye':[10.851,11.429],'Kaltungo':[9.819,11.308],'Kwami':[10.494,11.096],
  'Nafada':[11.095,11.332],'Shongom':[9.929,11.158],'Yamaltu/Deba':[10.211,11.386]
};
const T={
 en:{archive:'Pantami Legacy Digital Archive',tag:'Documenting public-service projects. Making the record searchable.',explore:'Explore the record',hausa:'Hausa',english:'English',projects:'Project entries indexed',appointments:'Appointments & employment opportunities stated in the compilation',years:'Public-service period covered',evidence:'Entries linked to source-page scans',search:'Search by project, place or keyword…',allCategories:'All categories',allLgas:'All locations',simple:'Simple view',details:'Evidence details',showEvidence:'Show evidence',source:'Source',bookPage:'Book page',pdfPage:'PDF page',documented:'Documented in report',notIndependent:'Independent verification not yet added',close:'Close',why:'What it means in everyday terms',map:'Explore by location',mapNote:'Pins show approximate LGA centres for browsing; they are not exact project coordinates.',timeline:'Legacy timeline',method:'Methodology & verification',about:'About this archive',featured:'Featured records',browse:'Browse all documented projects',noResults:'No projects match those filters.',cost:'Cost / value',agency:'Agency',year:'Year',status:'Status',location:'Location',record:'Record',lang:'Language',sourceScan:'Source scan',openScan:'Open full source scan',indexNote:'The project database was transcribed from the Table of Projects in the supplied compilation. Evidence pages are scans from that same document. Some fields remain intentionally blank until verified from a primary or independent source.',independent:'Verification layer',methodText:'Every entry begins as “documented in the supplied report.” The archive separates that from independent verification. Government-source confirmation, beneficiary confirmation and precise geolocation can be added later without changing the original record.',cta:'Don’t rely on summaries. Explore the record.'},
 ha:{archive:'Rumbun Ayyukan Gado na Pantami',tag:'Adana bayanan ayyukan jama’a. Sauƙaƙa bincike da ganin hujja.',explore:'Duba ayyukan',hausa:'Hausa',english:'English',projects:'Ayyukan da aka jera a kundin',appointments:'Nadin mukamai da damar aiki da kundin ya ambata',years:'Shekarun hidimar jama’a da kundin ya rufe',evidence:'Ayyukan da aka haɗa da hoton shafin madogara',search:'Nemo aiki, wuri ko kalma…',allCategories:'Dukkan rukuni',allLgas:'Dukkan wurare',simple:'Bayani mai sauƙi',details:'Cikakken bayani',showEvidence:'Duba shaida',source:'Madogara',bookPage:'Shafin littafi',pdfPage:'Shafin PDF',documented:'An rubuta a kundin',notIndependent:'Ba a ƙara tantancewa mai zaman kanta ba tukuna',close:'Rufe',why:'Ma’anarsa ga rayuwar yau da kullum',map:'Bincika ta wurin aiki',mapNote:'Alamomin taswira suna nuna kusan tsakiyar ƙananan hukumomi ne domin bincike; ba a ce su ne ainihin wurin kowanne aiki ba.',timeline:'Jadawalin lokaci',method:'Hanyar tantancewa',about:'Game da wannan rumbu',featured:'Wasu muhimman bayanai',browse:'Duba duk ayyukan da aka rubuta',noResults:'Babu aikin da ya dace da wannan binciken.',cost:'Kudin aiki / daraja',agency:'Hukuma',year:'Shekara',status:'Matsayi',location:'Wuri',record:'Bayanin aiki',lang:'Harshe',sourceScan:'Hoton shafin madogara',openScan:'Buɗe hoton shafin gaba ɗaya',indexNote:'An fitar da bayanan ayyukan daga “Table of Projects” na kundin da aka bayar. Hotunan shaida kuma daga wannan kundin suke. An bar wasu filaye babu bayani har sai an samu tabbaci daga madogarar hukuma ko wata hujja mai zaman kanta.',independent:'Matakin tabbatarwa',methodText:'Kowane aiki yana farawa da matsayin “an rubuta a kundin da aka bayar.” Wannan rumbu yana ware wannan daga tabbaci mai zaman kansa. Ana iya ƙara tabbatarwar hukuma, masu anfani da ainihin wurin aiki daga baya ba tare da canza asalin abin da kundin ya ce ba.',cta:'Kada ka tsaya kan ji kawai. Duba bayanan da kanka.'}
};
const categoryHa={'Broadband & Connectivity':'Sadarwa da Intanet','Digital Skills & Literacy':'Ƙwarewa da Ilimin Dijital','Digital Centres & Innovation':'Cibiyoyin Dijital da Kirkire-kirkire','Education & Devices':'Ilimi da Kayan Fasaha','Agriculture':'Noma','Health':'Lafiya','Jobs & Empowerment':'Aikin Yi da Ƙarfafawa','Public Infrastructure & Services':'Ababen More Rayuwa da Hidimar Jama’a','Economic Support & Welfare':'Tallafin Tattalin Arziki','Policy, Partnerships & Other':'Manufofi da Haɗin Gwiwa','Other Documented Projects':'Sauran Ayyuka'};
function App(){
 const [lang,setLang]=useState(localStorage.getItem('pl-lang')||'en'); const tr=T[lang];
 const [q,setQ]=useState(''); const [cat,setCat]=useState(''); const [lga,setLga]=useState(''); const [selected,setSelected]=useState(null); const [view,setView]=useState('simple');
 useEffect(()=>{localStorage.setItem('pl-lang',lang);document.documentElement.lang=lang==='ha'?'ha':'en'},[lang]);
 const categories=useMemo(()=>[...new Set(projects.map(p=>p.category))].sort(),[]); const locations=useMemo(()=>[...new Set(projects.map(p=>p.lga))].sort(),[]);
 const filtered=useMemo(()=>projects.filter(p=>{const s=(p.title+' '+p.titleHa+' '+p.category+' '+p.lga).toLowerCase();return (!q||s.includes(q.toLowerCase()))&&(!cat||p.category===cat)&&(!lga||p.lga===lga)}),[q,cat,lga]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(LGA_COORDS).map(k=>[k,projects.filter(p=>p.lga===k).length])),[]);
 const title=p=>lang==='ha'?p.titleHa:p.title;
 return <div>
  <header className="nav"><a className="brand" href="#top"><span className="mark">PL</span><span>{tr.archive}</span></a><nav><a href="#explore">{tr.explore}</a><a href="#map">{tr.map}</a><a href="#timeline">{tr.timeline}</a><a href="#method">{tr.method}</a></nav><button className="lang" onClick={()=>setLang(lang==='en'?'ha':'en')}>{lang==='en'?'HA':'EN'}</button></header>
  <main id="top">
   <section className="hero"><div className="heroCopy"><div className="eyebrow">2016—2023 · GOMBE STATE</div><h1>{tr.archive}</h1><p className="lead">{tr.tag}</p><div className="heroActions"><a className="primary" href="#explore">{tr.explore}</a><button className="secondary" onClick={()=>setLang(lang==='en'?'ha':'en')}>{lang==='en'?'Karanta da Hausa':'Read in English'}</button></div><div className="sourcePill">Source basis: <strong>Over 241 Transformative Legacy Projects of Professor Isa Ali Pantami in Gombe State (2016–2023)</strong></div></div><div className="portraitWrap"><img src="./assets/pantami-portrait.jpg" alt="Portrait reproduced from the supplied legacy document"/><div className="portraitCaption">Source image · supplied legacy compilation</div></div></section>
   <section className="stats"><Stat n="242" t={tr.projects}/><Stat n="700+" t={tr.appointments}/><Stat n="2016–2023" t={tr.years}/><Stat n="100%" t={tr.evidence}/></section>
   <section className="statement"><blockquote>“{tr.cta}”</blockquote><p>{tr.indexNote}</p></section>
   <section id="explore" className="section"><div className="sectionHead"><div><span className="eyebrow">DATABASE</span><h2>{tr.browse}</h2></div><div className="count">{filtered.length} / {projects.length}</div></div>
    <div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tr.search}/><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">{tr.allCategories}</option>{categories.map(c=><option key={c} value={c}>{lang==='ha'?(categoryHa[c]||c):c}</option>)}</select><select value={lga} onChange={e=>setLga(e.target.value)}><option value="">{tr.allLgas}</option>{locations.map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="viewTabs"><button className={view==='simple'?'active':''} onClick={()=>setView('simple')}>{tr.simple}</button><button className={view==='details'?'active':''} onClick={()=>setView('details')}>{tr.details}</button></div>
    <div className="grid">{filtered.length?filtered.map(p=><ProjectCard key={p.id} p={p} title={title(p)} lang={lang} tr={tr} details={view==='details'} onOpen={()=>setSelected(p)}/>):<div className="empty">{tr.noResults}</div>}</div>
   </section>
   <section id="map" className="section mapSection"><div className="sectionHead"><div><span className="eyebrow">GEOGRAPHY</span><h2>{tr.map}</h2><p>{tr.mapNote}</p></div></div><div className="mapShell"><MapContainer center={[10.28,11.18]} zoom={8.3} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{Object.entries(LGA_COORDS).map(([name,pos])=><CircleMarker key={name} center={pos} radius={Math.max(7,Math.min(19,6+(counts[name]||0)/3))} pathOptions={{color:'#0e5a3a',fillColor:'#d8a92f',fillOpacity:.8,weight:2}}><Popup><strong>{name}</strong><br/>{counts[name]||0} project entries<br/><button className="mapBtn" onClick={()=>{setLga(name);document.getElementById('explore')?.scrollIntoView({behavior:'smooth'})}}>Explore</button></Popup></CircleMarker>)}</MapContainer></div></section>
   <section id="timeline" className="section"><div className="sectionHead"><div><span className="eyebrow">PUBLIC SERVICE</span><h2>{tr.timeline}</h2></div></div><div className="timeline"><Milestone lang={lang} year="2016" en="Appointment as Director-General/CEO of NITDA; the compilation presents this as the starting point for many listed interventions." ha="An naɗa shi Darakta-Janar/CEO na NITDA; kundin ya nuna wannan a matsayin farkon yawancin ayyukan da aka jera." page="1–3"/><Milestone lang={lang} year="2019" en="Appointment as Minister of Communications; the ministry was later renamed Communications and Digital Economy." ha="An naɗa shi Ministan Sadarwa; daga baya aka sauya sunan ma’aikatar zuwa Sadarwa da Tattalin Arzikin Dijital." page="2–4"/><Milestone lang={lang} year="2022" en="The compilation records an FCDO/KPMG assessment across eight ministerial mandate areas and reports a 174% average score." ha="Kundin ya ambaci tantancewar FCDO/KPMG a fannoni takwas na aikin ma’aikata, tare da matsakaicin kashi 174%." page="5–6"/><Milestone lang={lang} year="2023" en="The compilation records the national honour Commander of the Order of the Niger (CON) and the end of the ministerial period covered by this archive." ha="Kundin ya rubuta karramawar Commander of the Order of the Niger (CON) da ƙarshen lokacin hidimar minista da wannan rumbu ya rufe." page="6–7"/></div></section>
   <section id="method" className="section method"><div><span className="eyebrow">TRANSPARENCY</span><h2>{tr.independent}</h2><p>{tr.methodText}</p><div className="badges"><span>✓ Report documented</span><span>□ Government-source confirmation</span><span>□ Beneficiary confirmation</span><span>□ Precise geolocation</span></div></div><img src="./assets/source-cover.jpg" alt="Cover of supplied legacy compilation"/></section>
  </main>
  <footer><strong>{tr.archive}</strong><span>Evidence-first · bilingual · GitHub Pages ready</span><span>This archive presents what the supplied compilation documents; it is not an independent audit.</span></footer>
  {selected&&<Modal p={selected} tr={tr} lang={lang} onClose={()=>setSelected(null)}/>} 
 </div>
}
function Stat({n,t}){return <div className="stat"><div>{n}</div><span>{t}</span></div>}
function ProjectCard({p,title,lang,tr,details,onOpen}){return <article className="card"><div className="cardTop"><span className="num">#{String(p.id).padStart(3,'0')}</span><span className="cat">{lang==='ha'?(categoryHa[p.category]||p.category):p.category}</span></div><h3>{title}</h3><p>{lang==='ha'?p.simpleHa:p.simpleEn}</p><div className="meta"><span>{p.lga}</span>{p.year&&<span>{p.year}</span>}{p.featured&&<span className="featured">Featured</span>}</div>{details&&<div className="detailMini"><b>{tr.source}:</b> book p. {p.evidencePage||'—'} · PDF p. {p.pdfPage||'—'}{p.cost&&<><br/><b>{tr.cost}:</b> {p.cost}</>}</div>}<button onClick={onOpen}>{tr.showEvidence} →</button></article>}
function Milestone({lang,year,en,ha,page}){return <div className="mile"><div className="year">{year}</div><div><p>{lang==='ha'?ha:en}</p><small>Source: Legacy compilation, book pp. {page}</small></div></div>}
function Modal({p,tr,lang,onClose}){useEffect(()=>{const h=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);const title=lang==='ha'?p.titleHa:p.title;return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="x" onClick={onClose}>×</button><div className="modalGrid"><div><span className="eyebrow">{tr.record} #{p.id}</span><h2>{title}</h2><p className="modalLead">{lang==='ha'?p.simpleHa:p.simpleEn}</p><h4>{tr.why}</h4><dl><dt>{tr.source}</dt><dd>Over 241 Transformative Legacy Projects…</dd><dt>{tr.bookPage}</dt><dd>{p.evidencePage||'—'}</dd><dt>{tr.pdfPage}</dt><dd>{p.pdfPage||'—'}</dd><dt>{tr.location}</dt><dd>{p.location||p.lga}</dd><dt>{tr.agency}</dt><dd>{p.agency||'—'}</dd><dt>{tr.year}</dt><dd>{p.year||'—'}</dd><dt>{tr.status}</dt><dd>{p.status}</dd><dt>{tr.cost}</dt><dd>{p.cost||'—'}</dd></dl><div className="verify"><span>✓ {tr.documented}</span><span>○ {tr.notIndependent}</span></div></div><div className="scan"><div className="scanLabel">{tr.sourceScan}</div>{p.pdfPage?<><img src={`./evidence/pdf-${p.pdfPage}.jpg`} alt={`Source PDF page ${p.pdfPage}`}/><a href={`./evidence/pdf-${p.pdfPage}.jpg`} target="_blank" rel="noreferrer">{tr.openScan} ↗</a></>:<div className="noScan">No page reference captured.</div>}</div></div></div></div>}
export default App;
