import React,{useEffect,useMemo,useState} from 'react';
import {MapContainer,TileLayer,CircleMarker,Popup} from 'react-leaflet';
import projects from './projects.json';
import {
  BIO_SECTIONS,ACHIEVEMENTS,NITDA_PILLARS,SCORECARD,POLICY_LEGACY,
  SERVICE_AREAS,RECOGNITIONS,INTERNATIONAL_COUNTRIES
} from './legacyContent.js';

const LGA_COORDS={
  'Gombe':[10.2897,11.1673],'Akko':[10.049,11.210],'Balanga':[9.887,11.544],'Billiri':[9.865,11.225],
  'Dukku':[10.823,10.772],'Funakaye':[10.851,11.429],'Kaltungo':[9.819,11.308],'Kwami':[10.494,11.096],
  'Nafada':[11.095,11.332],'Shongom':[9.929,11.158],'Yamaltu/Deba':[10.211,11.386]
};

const T={
 en:{
  archive:'Pantami Legacy Digital Archive',tag:'Documenting public-service projects, biography, service and achievements - with the source record attached.',
  explore:'Explore projects',bio:'Biography',achievements:'Achievements',service:'Service',policies:'Policy legacy',scorecard:'Scorecard',recognition:'Recognition',map:'Explore by location',timeline:'Timeline',method:'Verification',
  projects:'Project entries indexed',appointments:'Appointments & employment opportunities stated in the compilation',years:'Project period covered',evidence:'Project entries linked to evidence scans',
  search:'Search by project, place or keyword…',allCategories:'All categories',allLgas:'All locations',simple:'Simple view',details:'Evidence details',showEvidence:'Show evidence',
  source:'Source',bookPage:'Book page',pdfPage:'PDF page',documented:'Documented in report',notIndependent:'Independent verification not yet added',why:'What it means in everyday terms',
  browse:'Browse all documented projects',noResults:'No projects match those filters.',cost:'Cost / value',agency:'Agency',year:'Year',status:'Status',location:'Location',record:'Record',sourceScan:'Source scan',openScan:'Open full source scan',
  cta:'Don’t rely on summaries. Explore the record.',aboutTitle:'From biography to public service',aboutLead:'The source document contains more than project listings. It also presents a detailed biography, academic career, national service, policy reforms, professional qualifications, international roles and recognitions. This section brings those records into the archive.',
  achievementLead:'These figures are presented exactly as claims reported by the supplied compilation. They are not presented here as an independent audit.',
  serviceLead:'The document presents his public service through digital infrastructure, human capital, inclusion, innovation, jobs and non-ICT interventions.',
  policyLead:'The compilation connects the projects in Gombe to broader national policy and institutional reforms undertaken during his NITDA and ministerial service.',
  scoreLead:'The supplied document reproduces the following FCDO/KPMG ministerial mandate scores and states that the eight areas averaged 174%.',
  recognitionLead:'The biography and introductory chapters also record national honours, awards, academic distinctions and commendations.',
  international:'International footprint',internationalLead:'The biography lists visits and engagements across the following countries, among others.',
  biographySourceNote:'Biography content below follows the substance and sequence of the supplied document. The project period is 2016-2023, while the biography itself includes later updates through 2026.',
  sourceGallery:'Key source pages',sourceGalleryLead:'Open the original scanned pages used for the biography, service record, assessment and recognitions.',
  indexNote:'The project database was transcribed from the Table of Projects in the supplied compilation. Evidence pages are scans from that same document. Some fields remain intentionally blank until verified from a primary or independent source.',
  independent:'Verification layer',methodText:'Every entry begins as “documented in the supplied report.” The archive separates that from independent verification. Government-source confirmation, beneficiary confirmation and precise geolocation can be added later without changing the original record.',
  mapNote:'Pins show approximate LGA centres for browsing; they are not exact project coordinates.',
  sourceBasis:'Source basis',readSource:'View source page',asReported:'As reported by the compilation',publicService:'Public service',academic:'Academic & professional',updatedBio:'Biography includes source updates beyond 2023'
 },
 ha:{
  archive:'Rumbun Ayyukan Gado na Pantami',tag:'Adana ayyukan jama’a, tarihin rayuwa, hidima da nasarori - tare da madogarar da aka samo bayanin.',
  explore:'Duba ayyukan',bio:'Tarihin rayuwa',achievements:'Nasarori',service:'Hidima',policies:'Manufofi',scorecard:'Sakamakon aiki',recognition:'Karramawa',map:'Bincika ta wuri',timeline:'Jadawalin lokaci',method:'Tabbatarwa',
  projects:'Ayyukan da aka jera a kundin',appointments:'Nadin mukamai da damar aiki da kundin ya ambata',years:'Lokacin ayyukan da rumbun ya rufe',evidence:'Ayyukan da aka hada da hoton madogara',
  search:'Nemo aiki, wuri ko kalma…',allCategories:'Dukkan rukuni',allLgas:'Dukkan wurare',simple:'Bayani mai sauki',details:'Cikakken bayani',showEvidence:'Duba shaida',
  source:'Madogara',bookPage:'Shafin littafi',pdfPage:'Shafin PDF',documented:'An rubuta a kundin',notIndependent:'Ba a kara tantancewa mai zaman kanta ba tukuna',why:'Ma’anarsa ga rayuwar yau da kullum',
  browse:'Duba duk ayyukan da aka rubuta',noResults:'Babu aikin da ya dace da wannan binciken.',cost:'Kudin aiki / daraja',agency:'Hukuma',year:'Shekara',status:'Matsayi',location:'Wuri',record:'Bayanin aiki',sourceScan:'Hoton shafin madogara',openScan:'Bude hoton shafin gaba daya',
  cta:'Kada ka tsaya kan ji kawai. Duba bayanan da kanka.',aboutTitle:'Daga tarihin rayuwa zuwa hidimar jama’a',aboutLead:'Kundin bai tsaya kan jerin ayyuka kadai ba. Ya kunshi tarihin rayuwa, aikin jami’a, hidimar kasa, sauye-sauyen manufofi, kwarewa, ayyukan kasa da kasa da karramawa. Wannan sashe ya kawo wadannan bayanai cikin rumbun.',
  achievementLead:'Wadannan alkaluma su ne yadda kundin da aka bayar ya rubuta su. Ba a gabatar da su a matsayin bincike mai zaman kansa ba.',
  serviceLead:'Kundin ya gabatar da hidimar jama’a ta bangaren ababen more rayuwa na dijital, gina kwarewa, shigar da kowa, kirkire-kirkire, ayyukan yi da kuma wasu ayyukan da ba na ICT ba.',
  policyLead:'Kundin ya hada ayyukan Gombe da manyan manufofin kasa da sauye-sauyen hukumomi a lokacin NITDA da aikin minista.',
  scoreLead:'Takardar da aka bayar ta nuna wadannan sakamakon FCDO/KPMG kan manyan ayyukan ma’aikata guda takwas, kuma ta ce matsakaicinsu ya kai kashi 174%.',
  recognitionLead:'Tarihin rayuwa da babin gabatarwa sun kuma rubuta karramawar kasa, kyaututtuka, girmamawar ilimi da wasikun yabo.',
  international:'Kasashen da aka yi mu’amala da su',internationalLead:'Tarihin ya jera ziyara da mu’amala da wadannan kasashe, tare da wasu da ba a lissafa ba.',
  biographySourceNote:'Bayanin tarihin da ke kasa ya bi ma’ana da jerin bayanan kundin. Lokacin ayyukan rumbun shi ne 2016-2023, amma tarihin rayuwar kundin ya hada da sabbin bayanai har zuwa 2026.',
  sourceGallery:'Muhimman shafukan madogara',sourceGalleryLead:'Bude hotunan shafukan asali da aka yi amfani da su wajen tarihin rayuwa, hidima, tantancewa da karramawa.',
  indexNote:'An fitar da bayanan ayyukan daga “Table of Projects” na kundin da aka bayar. Hotunan shaida kuma daga wannan kundin suke. An bar wasu filaye babu bayani har sai an samu tabbaci daga madogarar hukuma ko wata hujja mai zaman kanta.',
  independent:'Matakin tabbatarwa',methodText:'Kowane aiki yana farawa da matsayin “an rubuta a kundin da aka bayar.” Wannan rumbu yana ware wannan daga tabbaci mai zaman kansa. Ana iya kara tabbatarwar hukuma, masu anfani da ainihin wurin aiki daga baya ba tare da canza asalin abin da kundin ya ce ba.',
  mapNote:'Alamomin taswira suna nuna kusan tsakiyar kananan hukumomi ne domin bincike; ba su ne ainihin wurin kowanne aiki ba.',
  sourceBasis:'Madogarar bayanai',readSource:'Duba shafin madogara',asReported:'Kamar yadda kundin ya rubuta',publicService:'Hidimar jama’a',academic:'Ilimi da kwarewa',updatedBio:'Tarihin ya hada da sabbin bayanai bayan 2023'
 }
};

const categoryHa={'Broadband & Connectivity':'Sadarwa da Intanet','Digital Skills & Literacy':'Kwarewa da Ilimin Dijital','Digital Centres & Innovation':'Cibiyoyin Dijital da Kirkire-kirkire','Education & Devices':'Ilimi da Kayan Fasaha','Agriculture':'Noma','Health':'Lafiya','Jobs & Empowerment':'Aikin Yi da Karfafawa','Public Infrastructure & Services':'Ababen More Rayuwa da Hidimar Jama’a','Economic Support & Welfare':'Tallafin Tattalin Arziki','Policy, Partnerships & Other':'Manufofi da Hadin Gwiwa','Other Documented Projects':'Sauran Ayyuka'};

function App(){
 const [lang,setLang]=useState(localStorage.getItem('pl-lang')||'en'); const tr=T[lang];
 const [q,setQ]=useState(''); const [cat,setCat]=useState(''); const [lga,setLga]=useState(''); const [selected,setSelected]=useState(null); const [view,setView]=useState('simple');
 useEffect(()=>{localStorage.setItem('pl-lang',lang);document.documentElement.lang=lang==='ha'?'ha':'en'},[lang]);
 const categories=useMemo(()=>[...new Set(projects.map(p=>p.category))].sort(),[]); const locations=useMemo(()=>[...new Set(projects.map(p=>p.lga))].sort(),[]);
 const filtered=useMemo(()=>projects.filter(p=>{const s=(p.title+' '+p.titleHa+' '+p.category+' '+p.lga).toLowerCase();return (!q||s.includes(q.toLowerCase()))&&(!cat||p.category===cat)&&(!lga||p.lga===lga)}),[q,cat,lga]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(LGA_COORDS).map(k=>[k,projects.filter(p=>p.lga===k).length])),[]);
 const title=p=>lang==='ha'?p.titleHa:p.title;
 return <div>
  <header className="nav"><a className="brand" href="#top"><span className="mark">PL</span><span>{tr.archive}</span></a><nav><a href="#biography">{tr.bio}</a><a href="#achievements">{tr.achievements}</a><a href="#service">{tr.service}</a><a href="#explore">{tr.explore}</a><a href="#method">{tr.method}</a></nav><button className="lang" onClick={()=>setLang(lang==='en'?'ha':'en')}>{lang==='en'?'HA':'EN'}</button></header>
  <main id="top">
   <section className="hero"><div className="heroCopy"><div className="eyebrow">2016-2023 · GOMBE STATE</div><h1>{tr.archive}</h1><p className="lead">{tr.tag}</p><div className="heroActions"><a className="primary" href="#biography">{tr.bio}</a><a className="secondary" href="#explore">{tr.explore}</a><button className="secondary" onClick={()=>setLang(lang==='en'?'ha':'en')}>{lang==='en'?'Karanta da Hausa':'Read in English'}</button></div><div className="sourcePill">{tr.sourceBasis}: <strong>Over 241 Transformative Legacy Projects of Professor Isa Ali Pantami in Gombe State (2016-2023)</strong></div></div><div className="portraitWrap"><img src="./assets/pantami-portrait.jpg" alt="Portrait reproduced from the supplied legacy document"/><div className="portraitCaption">{tr.asReported} · supplied legacy compilation</div></div></section>
   <section className="stats"><Stat n="242" t={tr.projects}/><Stat n="700+" t={tr.appointments}/><Stat n="2016-2023" t={tr.years}/><Stat n="100%" t={tr.evidence}/></section>
   <section className="statement"><blockquote>“{tr.cta}”</blockquote><p>{tr.indexNote}</p></section>

   <section id="biography" className="section biographySection">
    <div className="sectionHead"><div><span className="eyebrow">{tr.academic}</span><h2>{tr.aboutTitle}</h2><p>{tr.aboutLead}</p></div><div className="sourceTag">{tr.updatedBio}</div></div>
    <div className="bioIntro"><div className="bioPortrait"><img src="./assets/pantami-portrait.jpg" alt="Professor Isa Ali Ibrahim Pantami"/><div className="bioName"><strong>Professor Isa Ali Ibrahim Pantami, CON</strong><span>{lang==='ha'?'Malam · Masani · Mai tsara manufofi · Kwararre a fasaha':'Scholar · Policymaker · Technologist · Academic'}</span></div></div><div className="bioSummary"><p>{tr.biographySourceNote}</p><div className="bioQuick"><span>PhD · Computer Information Systems</span><span>DG/CEO NITDA · 2016-2019</span><span>Minister · 2019-2023</span><span>CON · 2023</span></div><EvidenceButton pdf={5} label={tr.readSource}/></div></div>
    <div className="bioSections">{BIO_SECTIONS.map((s,i)=><BiographyBlock key={i} section={s} lang={lang} tr={tr}/>)}</div>
   </section>

   <section id="achievements" className="section achievementsSection"><div className="sectionHead"><div><span className="eyebrow">{tr.asReported}</span><h2>{tr.achievements}</h2><p>{tr.achievementLead}</p></div></div><div className="achievementGrid">{ACHIEVEMENTS.map((a,i)=><Achievement key={i} a={a} lang={lang} tr={tr}/>)}</div></section>

   <section id="service" className="section serviceSection"><div className="sectionHead"><div><span className="eyebrow">{tr.publicService}</span><h2>{tr.service}</h2><p>{tr.serviceLead}</p></div></div><div className="serviceGrid">{SERVICE_AREAS.map((s,i)=><div className="serviceCard" key={i}><span className="serviceIcon">{s.icon}</span><h3>{lang==='ha'?s.titleHa:s.titleEn}</h3><p>{lang==='ha'?s.textHa:s.textEn}</p></div>)}</div></section>

   <section id="policies" className="section policySection"><div className="sectionHead"><div><span className="eyebrow">NITDA → DIGITAL ECONOMY</span><h2>{tr.policies}</h2><p>{tr.policyLead}</p></div></div><div className="pillarWrap"><div><h3>{lang==='ha'?'Ginshikai bakwai na taswirar NITDA':'Seven pillars of the NITDA roadmap'}</h3><p className="muted">{lang==='ha'?'Kamar yadda aka jera su a shafi na 2 na kundin.':'As listed on book page 2 of the compilation.'}</p></div><div className="pillars">{NITDA_PILLARS.map((p,i)=><div className="pillar" key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{lang==='ha'?p[1]:p[0]}</span></div>)}</div><EvidenceButton pdf={32} label={tr.readSource}/></div><div className="policyTimeline">{POLICY_LEGACY.map((p,i)=><div className="policyItem" key={i}><div className="policyYear">{p.year}</div><div><h3>{lang==='ha'?p.titleHa:p.titleEn}</h3><p>{lang==='ha'?p.textHa:p.textEn}</p><EvidenceButton pdf={p.pdf} label={tr.readSource}/></div></div>)}</div></section>

   <section id="scorecard" className="section scoreSection"><div className="sectionHead"><div><span className="eyebrow">FCDO / KPMG · SOURCE REPRODUCTION</span><h2>{tr.scorecard}</h2><p>{tr.scoreLead}</p></div><div className="scoreAverage"><strong>174%</strong><span>{lang==='ha'?'matsakaici a kundin':'average stated in compilation'}</span></div></div><div className="scoreTable">{SCORECARD.map((r,i)=><div className="scoreRow" key={i}><div className="scoreNo">{i+1}</div><div className="scoreLabel">{lang==='ha'?r[1]:r[0]}</div><div className="scoreBar"><i style={{width:`${Math.min(100,parseInt(r[2],10)/6)}%`}}></i></div><div className="scoreValue">{r[2]}</div></div>)}</div><div className="scoreSource"><EvidenceButton pdf={36} label={tr.readSource}/><span>{lang==='ha'?'Lura: kashi 594% ya wuce ma’aunin gani; an nuna shi yadda kundin ya rubuta.':'Note: the 594% value exceeds the visual scale; it is retained exactly as printed in the compilation.'}</span></div></section>

   <section id="recognition" className="section recognitionSection"><div className="sectionHead"><div><span className="eyebrow">HONOURS · ACADEMIA · COMMENDATIONS</span><h2>{tr.recognition}</h2><p>{tr.recognitionLead}</p></div></div><div className="recognitionGrid">{RECOGNITIONS.map((r,i)=><div className="recognitionCard" key={i}><div className="recognitionYear">{r.year}</div><h3>{lang==='ha'?r.titleHa:r.titleEn}</h3><p>{lang==='ha'?r.textHa:r.textEn}</p><EvidenceButton pdf={r.pdf} label={tr.readSource}/></div>)}</div></section>

   <section className="section internationalSection"><div className="sectionHead"><div><span className="eyebrow">GLOBAL ENGAGEMENT</span><h2>{tr.international}</h2><p>{tr.internationalLead}</p></div><EvidenceButton pdf={10} label={tr.readSource}/></div><div className="countries">{INTERNATIONAL_COUNTRIES.map(c=><span key={c}>{c}</span>)}</div></section>

   <section className="section gallerySection"><div className="sectionHead"><div><span className="eyebrow">DOCUMENTARY RECORD</span><h2>{tr.sourceGallery}</h2><p>{tr.sourceGalleryLead}</p></div></div><div className="sourceGallery">{[5,6,7,8,9,10,32,33,34,35,36,37,38,39,40,41,42,43].map(p=><a className="sourceThumb" href={`./evidence/pdf-${p}.jpg`} target="_blank" rel="noreferrer" key={p}><img src={`./evidence/pdf-${p}.jpg`} alt={`Source PDF page ${p}`}/><span>PDF {p}</span></a>)}</div></section>

   <section id="explore" className="section"><div className="sectionHead"><div><span className="eyebrow">DATABASE</span><h2>{tr.browse}</h2></div><div className="count">{filtered.length} / {projects.length}</div></div>
    <div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tr.search}/><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">{tr.allCategories}</option>{categories.map(c=><option key={c} value={c}>{lang==='ha'?(categoryHa[c]||c):c}</option>)}</select><select value={lga} onChange={e=>setLga(e.target.value)}><option value="">{tr.allLgas}</option>{locations.map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="viewTabs"><button className={view==='simple'?'active':''} onClick={()=>setView('simple')}>{tr.simple}</button><button className={view==='details'?'active':''} onClick={()=>setView('details')}>{tr.details}</button></div>
    <div className="grid">{filtered.length?filtered.map(p=><ProjectCard key={p.id} p={p} title={title(p)} lang={lang} tr={tr} details={view==='details'} onOpen={()=>setSelected(p)}/>):<div className="empty">{tr.noResults}</div>}</div>
   </section>

   <section id="map" className="section mapSection"><div className="sectionHead"><div><span className="eyebrow">GEOGRAPHY</span><h2>{tr.map}</h2><p>{tr.mapNote}</p></div></div><div className="mapShell"><MapContainer center={[10.28,11.18]} zoom={8.3} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{Object.entries(LGA_COORDS).map(([name,pos])=><CircleMarker key={name} center={pos} radius={Math.max(7,Math.min(19,6+(counts[name]||0)/3))} pathOptions={{color:'#0e5a3a',fillColor:'#d8a92f',fillOpacity:.8,weight:2}}><Popup><strong>{name}</strong><br/>{counts[name]||0} project entries<br/><button className="mapBtn" onClick={()=>{setLga(name);document.getElementById('explore')?.scrollIntoView({behavior:'smooth'})}}>Explore</button></Popup></CircleMarker>)}</MapContainer></div></section>

   <section id="timeline" className="section"><div className="sectionHead"><div><span className="eyebrow">PUBLIC SERVICE</span><h2>{tr.timeline}</h2></div></div><div className="timeline"><Milestone lang={lang} year="2016" en="Appointment as Director-General/CEO of NITDA; the compilation presents this as the starting point for many listed interventions." ha="An nada shi Darakta-Janar/CEO na NITDA; kundin ya nuna wannan a matsayin farkon yawancin ayyukan da aka jera." page="1-3"/><Milestone lang={lang} year="2019" en="Appointment as Minister of Communications; the ministry was later renamed Communications and Digital Economy." ha="An nada shi Ministan Sadarwa; daga baya aka sauya sunan ma’aikatar zuwa Sadarwa da Tattalin Arzikin Dijital." page="2-4"/><Milestone lang={lang} year="2022" en="The compilation records an FCDO/KPMG assessment across eight ministerial mandate areas and reports a 174% average score." ha="Kundin ya ambaci tantancewar FCDO/KPMG a fannoni takwas na aikin ma’aikata, tare da matsakaicin kashi 174%." page="5-6"/><Milestone lang={lang} year="2023" en="The compilation records the national honour Commander of the Order of the Niger (CON) and the end of the ministerial period covered by this archive." ha="Kundin ya rubuta karramawar Commander of the Order of the Niger (CON) da karshen lokacin hidimar minista da wannan rumbu ya rufe." page="6-7"/><Milestone lang={lang} year="2024-2026" en="The biography section includes later updates, including ASRIC/African Union and academic appointments, although these fall outside the 2016-2023 project period." ha="Sashen tarihin rayuwa ya hada da sabbin bayanai na 2024-2026, ciki har da ASRIC/African Union da wasu mukaman jami’a, duk da cewa wadannan sun wuce lokacin ayyukan 2016-2023." page="viii-ix"/></div></section>

   <section id="method" className="section method"><div><span className="eyebrow">TRANSPARENCY</span><h2>{tr.independent}</h2><p>{tr.methodText}</p><div className="badges"><span>✓ Report documented</span><span>□ Government-source confirmation</span><span>□ Beneficiary confirmation</span><span>□ Precise geolocation</span></div></div><img src="./assets/source-cover.jpg" alt="Cover of supplied legacy compilation"/></section>
  </main>
  <footer><strong>{tr.archive}</strong><span>Evidence-first · bilingual · searchable</span><span>{lang==='ha'?'Rumbun yana nuna abin da kundin da aka bayar ya rubuta; ba bincike mai zaman kansa ba ne.':'This archive presents what the supplied compilation documents; it is not an independent audit.'}</span></footer>
  {selected&&<Modal p={selected} tr={tr} lang={lang} onClose={()=>setSelected(null)}/>} 
 </div>
}

function Stat({n,t}){return <div className="stat"><div>{n}</div><span>{t}</span></div>}
function EvidenceButton({pdf,label}){return <a className="evidenceBtn" href={`./evidence/pdf-${pdf}.jpg`} target="_blank" rel="noreferrer">{label} · PDF {pdf} ↗</a>}
function BiographyBlock({section,lang,tr}){const paras=lang==='ha'?section.bodyHa:section.bodyEn;return <article className="bioBlock"><div className="bioBlockHead"><div><span className="eyebrow">{lang==='ha'?'Shafuka':'Book pages'} {section.pages}</span><h3>{lang==='ha'?section.titleHa:section.titleEn}</h3></div><div className="bioSources">{section.pdfPages.map(p=><EvidenceButton key={p} pdf={p} label={tr.readSource}/>)}</div></div>{paras.map((p,i)=><p key={i}>{p}</p>)}</article>}
function Achievement({a,lang,tr}){return <article className="achievement"><div className="achievementValue">{a.value}</div><p>{lang==='ha'?a.labelHa:a.labelEn}</p><EvidenceButton pdf={a.pdf} label={tr.readSource}/></article>}
function ProjectCard({p,title,lang,tr,details,onOpen}){return <article className="card"><div className="cardTop"><span className="num">#{String(p.id).padStart(3,'0')}</span><span className="cat">{lang==='ha'?(categoryHa[p.category]||p.category):p.category}</span></div><h3>{title}</h3><p>{lang==='ha'?p.simpleHa:p.simpleEn}</p><div className="meta"><span>{p.lga}</span>{p.year&&<span>{p.year}</span>}{p.featured&&<span className="featured">Featured</span>}</div>{details&&<div className="detailMini"><b>{tr.source}:</b> book p. {p.evidencePage||'—'} · PDF p. {p.pdfPage||'—'}{p.cost&&<><br/><b>{tr.cost}:</b> {p.cost}</>}</div>}<button onClick={onOpen}>{tr.showEvidence} →</button></article>}
function Milestone({lang,year,en,ha,page}){return <div className="mile"><div className="year">{year}</div><div><p>{lang==='ha'?ha:en}</p><small>Source: Legacy compilation, book pp. {page}</small></div></div>}
function Modal({p,tr,lang,onClose}){useEffect(()=>{const h=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[onClose]);const title=lang==='ha'?p.titleHa:p.title;return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="x" onClick={onClose}>×</button><div className="modalGrid"><div><span className="eyebrow">{tr.record} #{p.id}</span><h2>{title}</h2><p className="modalLead">{lang==='ha'?p.simpleHa:p.simpleEn}</p><h4>{tr.why}</h4><dl><dt>{tr.source}</dt><dd>Over 241 Transformative Legacy Projects…</dd><dt>{tr.bookPage}</dt><dd>{p.evidencePage||'—'}</dd><dt>{tr.pdfPage}</dt><dd>{p.pdfPage||'—'}</dd><dt>{tr.location}</dt><dd>{p.location||p.lga}</dd><dt>{tr.agency}</dt><dd>{p.agency||'—'}</dd><dt>{tr.year}</dt><dd>{p.year||'—'}</dd><dt>{tr.status}</dt><dd>{p.status}</dd><dt>{tr.cost}</dt><dd>{p.cost||'—'}</dd></dl><div className="verify"><span>✓ {tr.documented}</span><span>○ {tr.notIndependent}</span></div></div><div className="scan"><div className="scanLabel">{tr.sourceScan}</div>{p.pdfPage?<><img src={`./evidence/pdf-${p.pdfPage}.jpg`} alt={`Source PDF page ${p.pdfPage}`}/><a href={`./evidence/pdf-${p.pdfPage}.jpg`} target="_blank" rel="noreferrer">{tr.openScan} ↗</a></>:<div className="noScan">No page reference captured.</div>}</div></div></div></div>}
export default App;
